import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    centerCircle: {
        position: 'absolute',
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#f8f8f8',
        borderWidth: 2,
        borderColor: '#000',
        overflow: 'hidden',
        zIndex: 1,
        top: '50%',
        left: '50%',
        transform: [
            { translateX: -36 },
            { translateY: -35 }
        ],
    },
    centerQuadrants: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    quadrant: {
        width: '50%',
        height: '50%',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#000',
    },
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: '#e6e9f0',
    },
    cross: {
        position: "absolute",
        width: "90%",
        height: "90%",
        justifyContent: "center",
        alignItems: "center",
    },
    verticalContainer: {
        position: "absolute",
        top: 80,
        bottom: 80,
        width: 50,
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "center",
    },
    horizontalContainer: {
        position: "absolute",
        left: 80,
        right: 80,
        height: 50,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    verticalColumn: {
        width: "auto",
        padding: 3,
        marginHorizontal: 15,
    },
    horizontalRow: {
        width: "auto",
        padding: 3,
        marginVertical: 15,
        transform: [{ rotate: "-90deg" }],
    },
    verbBox: {
        backgroundColor: "#f0f4f8",
        borderWidth: 1,
        borderColor: "#d1d9e6",
        padding: 6,
        margin: 2,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    verbText: {
        textAlign: 'center',
        fontSize: 14,
    },
    controls: {
        position: 'absolute',
        bottom: -60,
        flexDirection: 'row',
        gap: 20,
        backgroundColor: '#ffffff',
        padding: 10,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#e8ecf4',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#d1d9e6',
        gap: 8,
    },
    buttonText: {
        fontSize: 16,
        color: '#2a3f5f',
        fontWeight: '500',
    },
});
