import { StyleSheet } from "react-native";

export const createLoginStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    keyboardView: {
      flex: 1,
    },
    content: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 24,
      paddingVertical: 32,
    },
    contentCompact: {
      paddingVertical: 20,
    },
    header: {
      alignItems: "center",
      marginBottom: 28,
    },
    logoShell: {
      width: 132,
      height: 132,
      borderRadius: 32,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 18,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 6,
    },
    logo: {
      width: 92,
      height: 92,
    },
    badge: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
    },
    title: {
      fontSize: 30,
      fontWeight: "800",
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: 10,
    },
    subtitle: {
      fontSize: 15,
      lineHeight: 22,
      color: theme.colors.textSecondary,
      textAlign: "center",
      maxWidth: 280,
    },
    actionsCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 18,
      gap: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 22,
      elevation: 5,
    },
    actionButton: {
      minHeight: 72,
      borderRadius: 18,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
    },
    actionButtonCompact: {
      minHeight: 64,
    },
    actionButtonDisabled: {
      opacity: 0.75,
    },
    primaryAction: {
      backgroundColor: theme.colors.accent,
    },
    secondaryAction: {
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    actionIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,255,255,0.18)",
      marginRight: 14,
    },
    secondaryActionIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.card,
      marginRight: 14,
    },
    actionText: {
      flex: 1,
      fontSize: 17,
      fontWeight: "700",
    },
    primaryActionText: {
      color: theme.colors.buttonText,
    },
    secondaryActionText: {
      color: theme.colors.text,
    },
    errorText: {
      fontSize: 14,
      lineHeight: 20,
      color: theme.colors.error,
      textAlign: "center",
      paddingTop: 4,
    },
  });
