# .eas/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main  # 👈 only deploy on main
jobs:
  deploy:
    type: deploy
    name: Deploy
    environment: production
    params:
      prod: true