# https://docs.expo.dev/eas/hosting/workflows/ test 2 pipeline for EAS Hosting deploys, triggered by GitHub Actions release workflow
name: Deploy

on:
  push:
    branches: ['main', 'release/*']
    tags: ['v*.*.*']
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel_in_progress: true

jobs:
  deploy:
    type: deploy
    name: Deploy
    environment: production
    params:
      prod: true
