import { StyleSheet } from 'react-native';

export const createWaitingRoomStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 24,
      backgroundColor: theme.colors.background,
    },
    header: {
      alignItems: 'center',
      marginBottom: 32,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: theme.colors.text,
    },
    subtitle: {
      fontSize: 16,
      color: theme.colors.textSecondary,
    },
    playersContainer: {
      flex: 1,
      borderRadius: 16,
      padding: 20,
      marginBottom: 24,
      backgroundColor: theme.colors.card,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    playersHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    playersTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.text,
    },
    refreshButton: {
      padding: 8,
    },
    refreshIndicator: {
      marginBottom: 16,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      padding: 24,
    },
    modalContainer: {
      width: '100%',
      maxWidth: 520,
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 24,
      borderColor: theme.colors.border,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 12,
      color: theme.colors.text,
      textAlign: 'center',
    },
    modalMessage: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      marginBottom: 20,
      textAlign: 'center',
    },
    modalButtonsColumn: {
      gap: 12,
      marginBottom: 16,
    },
    secondaryButton: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonText: {
      fontSize: 15,
      fontWeight: '600',
    },
    hostControls: {
      borderRadius: 14,
      padding: 14,
      marginBottom: 16,
      gap: 12,
    },
    hostControlsText: {
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
    addBotButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      gap: 8,
    },
    addBotButtonText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.buttonText,
    },
    playerItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 16,
      marginVertical: 6,
      borderRadius: 12,
    },
    playerDetails: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    playerAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    playerInitial: {
      color: 'white',
      fontSize: 20,
      fontWeight: 'bold',
    },
    playerName: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.text,
    },
    playerBadges: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    botBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    botBadgeText: {
      fontSize: 12,
      fontWeight: 'bold',
    },
    hostBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.colors.yellow,
    },
    hostBadgeText: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.text,
    },
    emptyText: {
      textAlign: 'center',
      padding: 24,
      fontStyle: 'italic',
      color: theme.colors.textSecondary,
    },
    joinInfo: {
      marginTop: 20,
      padding: 16,
      backgroundColor: theme.colors.inputBackground,
      borderRadius: 16,
    },
    joinInfoText: {
      textAlign: 'center',
      marginBottom: 8,
      color: theme.colors.textSecondary,
    },
    footer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    startButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      justifyContent: 'center',
      flex: 0.7,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    startButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 10,
      color: theme.colors.buttonText,
    },
    leaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      marginLeft: 12,
      justifyContent: 'center',
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    leaveButtonText: {
      fontSize: 14,
      marginLeft: 8,
      color: theme.colors.buttonText,
    },
    loadingText: {
      marginTop: 20,
      fontSize: 16,
      textAlign: 'center',
      color: theme.colors.textSecondary,
    },
    errorText: {
      fontSize: 18,
      textAlign: 'center',
      marginBottom: 20,
      color: theme.colors.error,
    },
    button: {
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: theme.colors.card,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.colors.text,
    },
    countdownContainer: {
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      padding: 20,
      borderRadius: 16,
      alignItems: 'center',
      position: 'absolute',
      top: '75%',
      alignSelf: 'center',
      zIndex: 1000,
      width: '85%',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 10,
    },
    countdownText: {
      color: 'white',
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  });
