import { StyleSheet } from 'react-native';

export const createHomeStyles = (theme, layout) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    contentContainer: {
      flexGrow: 1,
      paddingHorizontal: layout.horizontalPadding,
      paddingTop: layout.topPadding,
      paddingBottom: layout.bottomPadding,
      justifyContent: 'space-between',
      gap: layout.sectionGap,
    },
    header: {
      alignItems: 'center',
      marginBottom: layout.headerMarginBottom,
    },
    logo: {
      width: layout.logoSize,
      height: layout.logoSize,
    },
    title: {
      fontSize: layout.titleFontSize,
      fontWeight: 'bold',
      marginBottom: layout.titleMarginBottom,
      color: theme.colors.text,
      textAlign: 'center',
    },
    profileCard: {
      padding: layout.cardPadding,
      borderRadius: 16,
      marginBottom: layout.cardMarginBottom,
      backgroundColor: theme.colors.card,
      borderColor: theme.colors.border,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    profileHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    profileInfo: {
      flex: 1,
    },
    welcomeText: {
      fontSize: layout.welcomeFontSize,
      marginBottom: 8,
      color: theme.colors.textSecondary,
    },
    username: {
      fontSize: layout.usernameFontSize,
      fontWeight: '700',
      color: theme.colors.text,
    },
    guestBadge: {
      fontStyle: 'italic',
      fontWeight: '500',
      color: theme.colors.accent,
    },
    logoutButton: {
      padding: layout.logoutPadding,
      borderRadius: 24,
    },
    dashboard: {
      padding: layout.cardPadding,
      borderRadius: 16,
      marginBottom: layout.dashboardMarginBottom,
      backgroundColor: theme.colors.card,
      borderColor: theme.colors.border,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    dashboardTitle: {
      fontSize: layout.dashboardTitleFontSize,
      fontWeight: '600',
      marginBottom: layout.dashboardTitleMarginBottom,
      color: theme.colors.text,
    },
    statsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: layout.statsGap,
    },
    statItem: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
    },
    statValue: {
      fontSize: layout.statValueFontSize,
      fontWeight: 'bold',
      marginVertical: 8,
      color: theme.colors.text,
    },
    statLabel: {
      fontSize: layout.statLabelFontSize,
      textAlign: 'center',
      color: theme.colors.textSecondary,
    },
    buttonsContainer: {
      gap: layout.buttonsGap,
      marginBottom: layout.buttonsMarginBottom,
    },
    button: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: layout.buttonVerticalPadding,
      paddingHorizontal: layout.buttonHorizontalPadding,
      borderRadius: 16,
      gap: layout.buttonGap,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    buttonPrimary: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.border,
      borderWidth: 1,
    },
    buttonSecondary: {
      backgroundColor: theme.colors.card,
      borderColor: theme.colors.border,
      borderWidth: 1,
    },
    buttonText: {
      fontSize: layout.buttonTextFontSize,
      fontWeight: '600',
      textAlign: 'center',
    },
    buttonTextPrimary: {
      color: theme.colors.buttonText,
    },
    buttonTextSecondary: {
      color: theme.colors.text,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.background,
      padding: 24,
    },
    modalContainer: {
      width: '100%',
      maxWidth: 520,
      alignSelf: 'center',
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 24,
      borderColor: theme.colors.border,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 12,
      color: theme.colors.text,
      textAlign: 'center',
    },
    modalMessage: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      marginBottom: 24,
      textAlign: 'center',
    },
    modalButtonsRow: {
      flexDirection: 'column',
      gap: 12,
      marginBottom: 16,
    },
    optionButton: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      backgroundColor: theme.colors.success,
      borderColor: theme.colors.border,
      borderWidth: 1,
    },
    optionButtonText: {
      fontSize: 16,
      color: theme.colors.buttonText,
      fontWeight: '700',
    },
    cancelButton: {
      backgroundColor: theme.colors.card,
      borderColor: theme.colors.border,
      borderWidth: 1,
    },
    footer: {
      alignItems: 'center',
      paddingTop: layout.footerPaddingTop,
    },
    footerText: {
      fontSize: layout.footerFontSize,
      textAlign: 'center',
      color: theme.colors.textSecondary,
    },
  });
